version: '2'

services:
    sabnzbd:
        image: linuxserver/sabnzbd
        container_name: sabnzbd
        restart: always
        networks:
            - media        
        ports:
            - 8008:8080
            - 9009:9090
        volumes:
            - /srv/appdata/sabnzbd:/config
            - /srv/downloads/complete:/downloads
            - /srv/downloads/incomplete:/incomplete-downloads
        environment:
            PUID: ${userid}
            PGID: ${groupid}
            TZ: ${time}

networks:
    media:
        external: true              